# -*- coding: utf-8 -*-
"""DATA_abstraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k-xTi9qBMzwmiHSuKl14blrAKo3jUNMi

**STATIC METHOD IN PYTHON**
"""

class student:
  def __init__(self,name,age):
    self.name=name
    self.age=age
  def details(self):
    return print("Name :",self.name,"Age :",self.age)
  @staticmethod
  def welcome():
    return print("welcome to our institution")

s1=student("sona",22)
s1.details()
s1.welcome()

"""# **Data abstarction and encapsulation**"""

class library:
  def __init__(self,books):
    self.books=books

  def list_book(self):
    print("available books is")
    for book in self.books:
      print(book)

  def borrow_book(self,borrow_book):
    if borrow_book in self.books:
      print("get your books")
      self.books.remove(borrow_book)
    else:
      print("book not available")
  def received_book(self,received_book):
    print("you have return the book")
    self.books.append(received_book)


books=["python","java","c++","c","javascript"]
o=library(books)

msg= """
1.Display book
2.borrow book
3return book
"""

while True:
  print(msg)
  ch = int(input("enter your choice :"))
  if ch==1 :
    o.list_book()
  elif ch==2:
    book = input("enter your book name to borrow")
    o.borrow_book(book)
  elif ch==3:
    book=input("enter the book name to return")
    o.received_book(book)
  else:
    print("THANK YOU COME AGAIN")
    break

