# -*- coding: utf-8 -*-
"""Function_overiding and diamondproblem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/196k-QoMizoOM3jE3cCM-0yzPz1S0QH1O

# **FUNCTION OVERRINDING**
"""

class Employee:
  def workingHrs(self):
    self.hrs=50
  def printHrs(self):
    print("Total woking hours :",self.hrs)

class Trainee(Employee):
  def workingHrs(self):
    self.hrs=60

  def resetHRs(self):
    super().workingHrs()

employee =Employee()
employee.workingHrs()
employee.printHrs()

trainee = Trainee()
trainee.workingHrs()
trainee.printHrs()


#reset trainee hrs
trainee.resetHRs()
trainee.printHrs()

"""# **Diamond problem**"""

class A:
  def display(self):
    print("Display the class A")

class B(A):
  def display(self):
    print("Display the class B")

class C(A):
  def display(self):
    print("Display the class C")

class D(B,C):
  def display(self):
    print("Display the class D")


o=D()
o.display()