# -*- coding: utf-8 -*-
"""inheritance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FNMkdbmCwn1LJIkSEB-5JIpz5XwWFmVb

# **SINGLE INHERITANCE**
"""

class vivo:
  company = "vivo india"
  website = "www.vivo-india.com"
  def contact_details(self):
    print("Adress: cherry Road , Near Bus , Salem")

class vivoA5(vivo):
  def __init__(self):
    self.name="Vivo A5"
    self.year="2018"
  def product_details(self):
    print("Name : ",self.name)
    print("Year :",self.year)
    print("Company :",self.company)
    print("website :",self.website)

mobile = vivoA5()
mobile.product_details()
mobile.contact_details()

"""# **MULTIPLE INHERITANCE**"""

class father:
  def drive(self):
    print("Father is well drive the car")

  def chess(self):
    print("father know chess very well")

class mother:
  def cooking(self):
    print("mother is expert in cooking")

  def chess(self):
    print("mother know chess very well")


class son(father,mother):
  def swimming(self):
    print("son swims very well")

o= son()
o.swimming()
o.drive()
o.cooking()
o.chess()

"""# **MULTILEVEL INHERITANCE**"""

class GrandFather:
  def ownHouse(self):
    print("Grandpa's house")

class Father(GrandFather):
  def ownBike(self):
    print("Father having own bike")

class son(Father):
  def bookShop(self):
    print("son having own house")

o=son()
o.bookShop()
o.ownHouse()
o.ownBike()